package io.github.dungeonsworkshop.mapbuilder.MCUtils.enums;

public enum DungeonsBlock {

    AIR(0x00,"minecraft:air"),
    STONE(0x01,"minecraft:stone"),
    DIORITE(0x01,"minecraft:diorite"),
    GRANITE(0x01,"minecraft:granite"),
    ANDESITE(0x01,"minecraft:andesite"),
    GRASS_BLOCK(0x02,"minecraft:grass_block"),
    DIRT(0x03,"minecraft:dirt"),
    COARSE_DIRT(-0x20,"minecraft:coarse_dirt"),
    COBBLESTONE(0x04, "minecraft:cobblestone"),
    OAK_PLANKS(0x05,"minecraft:oak_planks"),
    OAK_SAPLING(0x06,"minecraft:oak_sapling"),
    WATER(0x09, "minecraft:water"),
    SAND(0x0c,"minecraft:sand"),
    OAK_LOG(0x11,"minecraft:oak_log"),
    OAK_LEAVES(0x12, "mineacraft:oak_leaves"),
    SANDSTONE(0x18,"minecraft:sandstone"),
    GRASS(0x1f, "minecraft:grass"),
    DANDELION(0x25, "minecraft:dandelion"),
    POPPY(0x26, "minecraft:poppy"),
    SMOOTH_STONE_SLAB_TOP(0x2b, "minecraft:smooth_stone_slab", SlabType.DOUBLE),
    SMOOTH_STONE_SLAB_BOTTOM(0x2c, "minecraft:smooth_stone_slab", SlabType.BOTTOM),
    MOSSY_COBBLESTONE(0x30, "minecraft:mossy_cobblestone"),
    WHEAT(0x3b, "minecraft:wheat"),
    FARMLAND(0x3c, "minecraft:farmland"),
    COBBLESTONE_STAIRS(0x43, "minecraft:cobblestone_stairs"),
    OAK_FENCE(0x55, "minecraft:oak_fence"),
    OAK_TRAPDOOR(0x60, "minecraft:oak_trapdoor"),
    STONE_BRICKS(0x62, "minecraft:stone_bricks"),
    GLASS_PANE(0x66, "minecraft:glass_pane"),
    PUMPKIN_STEM(0x68, "minecraft:pumpkin_stem"),
    VINE(0x6a, "minecraft:vine"),
    STONE_BRICK_STAIRS(0x6d, "minecraft:stone_brick_stairs"),
    MYCELIUM(0x6e, "minecraft:mycelium"),
    PODZOL(-0x0d, "minecraft:podzol"),
    SPRUCE_STAIRS(0x86, "minecraft:spruce_stairs"),
    PLANKS(0x05, "minecraft:oak_planks"),
    SAPLING(0x06, "minecraft:oak_sapling"),
    FLOWING_WATER(0x08, "minecraft:flowing_water"),
    FLOWING_LAVA(0x0A, "minecraft:flowing_lava"),
    LAVA(0x0B, "minecraft:lava"),
    LOG(0x11, "minecraft:oak_log"),
    LEAVES(0x12, "minecraft:oak_leaves"),
    LAPIS_ORE(0x15, "minecraft:lapis_ore"),
    LAPIS_BLOCK(0x16, "minecraft:lapis_block"),
    NOTEBLOCK(0x19, "minecraft:note_block"),
    BED(0x1A, "minecraft:red_bed"),
    GOLDEN_RAIL(0x1B, "minecraft:powered_rail"),
    DETECTOR_RAIL(0x1C, "minecraft:detector_rail"),
    WEB(0x1E, "minecraft:cobweb"),
    TALLGRASS(0x1F, "minecraft:tall_grass"),
    DEADBUSH(0x20, "minecraft:dead_bush"),
    PISTON_HEAD(0x22, "minecraft:piston_head"),
    WOOL(0x23, "minecraft:white_wool"),
    PISTON_EXTENSION(0x24, "minecraft:piston_extension"),
    YELLOW_FLOWER(0x25, "minecraft:dandelion"),
    RED_FLOWER(0x26, "minecraft:poppy"),
    BROWN_MUSHROOM(0x27, "minecraft:brown_mushroom"),
    RED_MUSHROOM(0x28, "minecraft:red_mushroom"),
    GOLD_BLOCK(0x29, "minecraft:gold_block"),
    IRON_BLOCK(0x2A, "minecraft:iron_block"),
    DOUBLE_STONE_SLAB(0x2B, "minecraft:stone_slab"),
    BRICK_BLOCK(0x2D, "minecraft:bricks"),
    FIRE(0x33, "minecraft:fire"),
    MOB_SPAWNER(0x34, "minecraft:spawner"),
    OAK_STAIRS(0x35, "minecraft:oak_stairs"),
    REDSTONE_WIRE(0x37, "minecraft:redstone"),
    DIAMOND_BLOCK(0x39, "minecraft:diamond_block"),
    LIT_FURNACE(0x3E, "minecraft:furnace"),
    STANDING_SIGN(0x3F, "minecraft:oak_sign"),
    WOODEN_DOOR(0x40, "minecraft:oak_door"),
    RAIL(0x42, "minecraft:rail"),
    WALL_SIGN(0x44, "minecraft:oak_wall_sign"),
    WOODEN_PRESSURE_PLATE(0x48, "minecraft:oak_pressure_plate"),
    LIT_REDSTONE_ORE(0x4A, "minecraft:redstone_ore"),
    UNLIT_REDSTONE_TORCH(0x4B, "minecraft:redstone_torch"),
    SNOW_LAYER(0x4E, "minecraft:snow"),
    REEDS(0x53, "minecraft:sugar_cane"),
    FENCE(0x55, "minecraft:oak_fence"),
    PORTAL(0x5A, "minecraft:portal"),
    LIT_PUMPKIN(0x5B, "minecraft:jack_o_lantern"),
    UNPOWERED_REPEATER(0x5D, "minecraft:repeater"),
    POWERED_REPEATER(0x5E, "minecraft:repeater"),
    STAINED_GLASS(0x5F, "minecraft:white_stained_glass"),
    TRAPDOOR(0x60, "minecraft:oak_trapdoor"),
    MONSTER_EGG(0x61, "minecraft:dragon_egg"),
    STONEBRICKS(0x62, "minecraft:stone_bricks"),
    MOSSY_STONE_BRICKC(0x62, "minecraft:mossy_stone_bricks"),
    MELON_BLOCK(0x67, "minecraft:melon"),
    MELON_STEM(0x69, "minecraft:melon_stem"),
    FENCE_GATE(0x6B, "minecraft:oak_fence_gate"),
    WATERLILY(0x6F, "minecraft:lily_pad"),
    END_PORTAL(0x77, "minecraft:end_portal"),
    POWERED_REDSTONE_LAMP(0x7C, "minecraft:redstone_lamp"),
    DOUBLE_WOODEN_SLAB(0x7D, "minecraft:oak_slab"),
    WOODEN_SLAB(0x7E, "minecraft:oak_slab"),
    COCOA(0x7F, "minecraft:cocoa"),
    TRIPWIRE(0x84, "minecraft:tripwire"),
    EMERALD_BLOCK(0x85, "minecraft:emerald_block"),
    BIRCH_STAIRS(0x87, "minecraft:birch_stairs"),
    JUNGLE_STAIRS(0x88, "minecraft:jungle_stairs"),
    CARROTS(0x8D, "minecraft:carrots"),
    POTATOES(0x8E, "minecraft:potatoes"),
    SKULL(0x90, "minecraft:skeleton_skull"),
    UNPOWERED_COMPARATOR(0x95, "minecraft:comparator"),
    POWERED_COMPARATOR(0x96, "minecraft:comparator"),
    DAYLIGHT_DETECTOR(0x97, "minecraft:daylight_detector"),
    REDSTONE_BLOCK(0x98, "minecraft:redstone_block"),
    QUARTZ_ORE(0x99, "minecraft:nether_quartz_ore"),
    QUARTZ_BLOCK(0x9B, "minecraft:quartz_block"),
    ACTIVATOR_RAIL(0x9D, "minecraft:activator_rail"),
    STAINED_HARDENED_CLAY(0x9F, "minecraft:white_terracotta"),
    STAINED_GLASS_PANE(0xA0, "minecraft:white_stained_glasspane"),
    LEAVES2(0xA1, "minecraft:dark_oak_leaves"),
    LOG2(0xA2, "minecraft:dark_oak_log"),
    ACACIA_STAIRS(0xA3, "minecraft:acacia_stairs"),
    DARK_OAK_STAIRS(0xA4, "minecraft:dark_oak_stairs"),
    SLIME(0xA5, "minecraft:slime_block"),
    HAY_BLOCK(0xAA, "minecraft:hay_block"),
    CARPET(0xAB, "minecraft:white_carpet"),
    HARDENED_CLAY(0xAC, "minecraft:terracottta"),
    DOUBLE_PLANT(0xAF, "minecraft:tall_grass"),
    STANDING_BANNER(0xB0, "minecraft:white_banner"),
    WALL_BANNER(0xB1, "minecraft:white_wall_banner"),
    DAYLIGHT_DETECTOR_INVERTED(0xB2, "minecraft:daylight_detector"),
    DOUBLE_STONE_SLAB2(0xB5, "minecraft:smooth_stone_slab"),
    STONE_SLAB2(0xB6, "minecraft:smooth_stone_slab"),
    PURPUR_DOUBLE_SLAB(0xCC, "minecraft:purpur_slab"),
    END_BRICKS(0xCE, "minecraft:end_stone_bricks"),
    BEETROOTS(0xCF, "minecraft:beetroots"),
    END_GATEWAY(0xD1, "minecraft:end_gateway"),
    FROSTED_ICE(0xD4, "minecraft:frosted_ice"),
    MAGMA(0xD5, "minecraft:magma_block"),
    SILVER_SHULKER_BOX(0xE3, "minecraft:light_gray_shulker_box"),
    SILVER_GLAZED_TERRACOTTA(0xF3, "minecraft:light_gray_glazed_terracotta"),
    CONCRETE(0xFB, "minecraft:white_concrete"),
    CONCRETE_POWDER(0xFC, "minecraft:white_concrete_powder"),
    ACACIA_DOOR(0xC4, "minecraft:acacia_door"),
    ACACIA_FENCE(0xC0, "minecraft:acacia_fence"),
    ACACIA_FENCE_GATE(0xBB, "minecraft:acacia_fence_gate"),
    ANVIL(0x91, "minecraft:anvil"),
    BARRIER(0xA6, "minecraft:barrier"),
    BEACON(0x8A, "minecraft:beacon"),
    BEDROCK(0x07, "minecraft:bedrock"),
    BIRCH_DOOR(0xC2, "minecraft:birch_door"),
    BIRCH_FENCE(0xBD, "minecraft:birch_fence"),
    BIRCH_FENCE_GATE(0xB8, "minecraft:birch_fence_gate"),
    BLACK_GLAZED_TERRACOTTA(0xFA, "minecraft:black_glazed_terracotta"),
    BLACK_SHULKER_BOX(0xEA, "minecraft:black_shulker_box"),
    BLUE_GLAZED_TERRACOTTA(0xF6, "minecraft:blue_glazed_terracotta"),
    BLUE_SHULKER_BOX(0xE6, "minecraft:blue_shulker_box"),
    BONE_BLOCK(0xD8, "minecraft:bone_block"),
    BOOKSHELF(0x2F, "minecraft:bookshelf"),
    BREWING_STAND(0x75, "minecraft:brewing_stand"),
    BRICK_STAIRS(0x6C, "minecraft:brick_stairs"),
    BROWN_GLAZED_TERRACOTTA(0xF7, "minecraft:brown_glazed_terracotta"),
    BROWN_MUSHROOM_BLOCK(0x63, "minecraft:brown_mushroom_block"),
    BROWN_SHULKER_BOX(0xE7, "minecraft:brown_shulker_box"),
    CACTUS(0x51, "minecraft:cactus"),
    CAKE(0x5C, "minecraft:cake"),
    CAULDRON(0x76, "minecraft:cauldron"),
    CHAIN_COMMAND_BLOCK(0xD3, "minecraft:chain_command_block"),
    CHEST(0x36, "minecraft:chest"),
    CHORUS_FLOWER(0xC8, "minecraft:chorus_flower"),
    CHORUS_PLANT(0xC7, "minecraft:chorus_plant"),
    CLAY(0x52, "minecraft:clay_ball"),
    COAL_BLOCK(0xAD, "minecraft:coal_block"),
    COAL_ORE(0x10, "minecraft:coal_ore"),
    COBBLESTONE_WALL(0x8B, "minecraft:cobblestone_wall"),
    COMMAND_BLOCK(0x89, "minecraft:command_block"),
    CRAFTING_TABLE(0x3A, "minecraft:crafting_table"),
    CYAN_GLAZED_TERRACOTTA(0xF4, "minecraft:cyan_glazed_terracotta"),
    CYAN_SHULKER_BOX(0xE4, "minecraft:cyan_shulker_box"),
    DARK_OAK_DOOR(0xC5, "minecraft:dark_oak_door"),
    DARK_OAK_FENCE(0xBF, "minecraft:dark_oak_fence"),
    DARK_OAK_FENCE_GATE(0xBA, "minecraft:dark_oak_fence_gate"),
    DIAMOND_ORE(0x38, "minecraft:diamond_ore"),
    DISPENSER(0x17, "minecraft:dispenser"),
    DRAGON_EGG(0x7A, "minecraft:dragon_egg"),
    DROPPER(0x9E, "minecraft:dropper"),
    EMERALD_ORE(0x81, "minecraft:emerald_ore"),
    ENCHANTING_TABLE(0x74, "minecraft:enchanting_table"),
    END_PORTAL_FRAME(0x78, "minecraft:end_portal_frame"),
    END_ROD(0xC6, "minecraft:end_rod"),
    END_STONE(0x79, "minecraft:end_stone"),
    ENDER_CHEST(0x82, "minecraft:ender_chest"),
    FLOWER_POT(0x8C, "minecraft:flower_pot"),
    FURNACE(0x3D, "minecraft:furnace"),
    GLASS(0x14, "minecraft:glass"),
    GLOWSTONE(0x59, "minecraft:glowstone"),
    GOLD_ORE(0x0E, "minecraft:gold_ore"),
    GRASS_PATH(0xD0, "minecraft:grass_path"),
    GRAVEL(0x0D, "minecraft:gravel"),
    GRAY_GLAZED_TERRACOTTA(0xF2, "minecraft:gray_glazed_terracotta"),
    GRAY_SHULKER_BOX(0xE2, "minecraft:gray_shulker_box"),
    GREEN_GLAZED_TERRACOTTA(0xF8, "minecraft:green_glazed_terracotta"),
    GREEN_SHULKER_BOX(0xE8, "minecraft:green_shulker_box"),
    HEAVY_WEIGHTED_PRESSURE_PLATE(0x94, "minecraft:heavy_weighted_pressure_plate"),
    HOPPER(0x9A, "minecraft:hopper"),
    ICE(0x4F, "minecraft:ice"),
    IRON_BARS(0x65, "minecraft:iron_bars"),
    IRON_DOOR(0x47, "minecraft:iron_door"),
    IRON_ORE(0x0F, "minecraft:iron_ore"),
    IRON_TRAPDOOR(0xA7, "minecraft:iron_trapdoor"),
    JUKEBOX(0x54, "minecraft:jukebox"),
    JUNGLE_DOOR(0xC3, "minecraft:jungle_door"),
    JUNGLE_FENCE(0xBE, "minecraft:jungle_fence"),
    JUNGLE_FENCE_GATE(0xB9, "minecraft:jungle_fence_gate"),
    LADDER(0x41, "minecraft:ladder"),
    LEVER(0x45, "minecraft:lever"),
    LIGHT_BLUE_GLAZED_TERRACOTTA(0xEE, "minecraft:light_blue_glazed_terracotta"),
    LIGHT_BLUE_SHULKER_BOX(0xDE, "minecraft:light_blue_shulker_box"),
    LIGHT_WEIGHTED_PRESSURE_PLATE(0x93, "minecraft:light_weighted_pressure_plate"),
    LIME_GLAZED_TERRACOTTA(0xF0, "minecraft:lime_glazed_terracotta"),
    LIME_SHULKER_BOX(0xE0, "minecraft:lime_shulker_box"),
    MAGENTA_GLAZED_TERRACOTTA(0xED, "minecraft:magenta_glazed_terracotta"),
    MAGENTA_SHULKER_BOX(0xDD, "minecraft:magenta_shulker_box"),
    NETHER_BRICK(0x70, "minecraft:nether_brick"),
    NETHER_BRICK_FENCE(0x71, "minecraft:nether_brick_fence"),
    NETHER_BRICK_STAIRS(0x72, "minecraft:nether_brick_stairs"),
    NETHER_WART(0x73, "minecraft:nether_wart"),
    NETHER_WART_BLOCK(0xD6, "minecraft:nether_wart_block"),
    NETHERRACK(0x57, "minecraft:netherrack"),
    OAK_BUTTON(0x8F, "minecraft:oak_button"),
    OBSERVER(0xDA, "minecraft:observer"),
    OBSIDIAN(0x31, "minecraft:obsidian"),
    ORANGE_GLAZED_TERRACOTTA(0xEC, "minecraft:orange_glazed_terracotta"),
    ORANGE_SHULKER_BOX(0xDC, "minecraft:orange_shulker_box"),
    PACKED_ICE(0xAE, "minecraft:packed_ice"),
    PINK_GLAZED_TERRACOTTA(0xF1, "minecraft:pink_glazed_terracotta"),
    PINK_SHULKER_BOX(0xE1, "minecraft:pink_shulker_box"),
    PISTON(0x21, "minecraft:piston"),
    PRISMARINE(0xA8, "minecraft:prismarine"),
    PUMPKIN(0x56, "minecraft:pumpkin"),
    PURPLE_GLAZED_TERRACOTTA(0xF5, "minecraft:purple_glazed_terracotta"),
    PURPLE_SHULKER_BOX(0xE5, "minecraft:purple_shulker_box"),
    PURPUR_BLOCK(0xC9, "minecraft:purpur_block"),
    PURPUR_PILLAR(0xCA, "minecraft:purpur_pillar"),
    PURPUR_SLAB(0xCD, "minecraft:purpur_slab"),
    PURPUR_STAIRS(0xCB, "minecraft:purpur_stairs"),
    QUARTZ_STAIRS(0x9C, "minecraft:quartz_stairs"),
    RED_GLAZED_TERRACOTTA(0xF9, "minecraft:red_glazed_terracotta"),
    RED_MUSHROOM_BLOCK(0x64, "minecraft:red_mushroom_block"),
    RED_NETHER_BRICK(0xD7, "minecraft:red_nether_bricks"),
    RED_SANDSTONE(0xB3, "minecraft:red_sandstone"),
    RED_SANDSTONE_STAIRS(0xB4, "minecraft:red_sandstone_stairs"),
    RED_SHULKER_BOX(0xE9, "minecraft:red_shulker_box"),
    REDSTONE_LAMP(0x7B, "minecraft:redstone_lamp"),
    REDSTONE_ORE(0x49, "minecraft:redstone_ore"),
    REDSTONE_TORCH(0x4C, "minecraft:redstone_torch"),
    REPEATING_COMMAND_BLOCK(0xD2, "minecraft:repeating_command_block"),
    SANDSTONE_STAIRS(0x80, "minecraft:sandstone_stairs"),
    SEA_LANTERN(0xA9, "minecraft:sea_lantern"),
    SNOW(0x50, "minecraft:snow"),
    SOUL_SAND(0x58, "minecraft:soul_sand"),
    SPONGE(0x13, "minecraft:sponge"),
    SPRUCE_DOOR(0xC1, "minecraft:spruce_door"),
    SPRUCE_FENCE(0xBC, "minecraft:spruce_fence"),
    SPRUCE_FENCE_GATE(0xB7, "minecraft:spruce_fence_gate"),
    STICKY_PISTON(0x1D, "minecraft:sticky_piston"),
    STONE_BUTTON(0x4D, "minecraft:stone_button"),
    STONE_PRESSURE_PLATE(0x46, "minecraft:stone_pressure_plate"),
    STONE_SLAB(0x2C, "minecraft:stone_slab"),
    STONE_STAIRS(0x43, "minecraft:stone_stairs"),
    STRUCTURE_BLOCK(0xFF, "minecraft:structure_block"),
    STRUCTURE_VOID(0xD9, "minecraft:structure_void"),
    TNT(0x2E, "minecraft:tnt"),
    TORCH(0x32, "minecraft:torch"),
    TRAPPED_CHEST(0x92, "minecraft:trapped_chest"),
    TRIPWIRE_HOOK(0x83, "minecraft:tripwire_hook"),
    WHITE_GLAZED_TERRACOTTA(0xEB, "minecraft:white_glazed_terracotta"),
    WHITE_SHULKER_BOX(0xDB, "minecraft:white_shulker_box"),
    YELLOW_GLAZED_TERRACOTTA(0xEF, "minecraft:yellow_glazed_terracotta"),
    YELLOW_SHULKER_BOX(0xDF, "minecraft:yellow_shulker_box");

    private int hex;
    private String namespaceID;
    private Object data;

    DungeonsBlock(int hex, String namespaceID){
        this.hex = hex;
        this.namespaceID = namespaceID;
        this.data = null;
    }

    DungeonsBlock(int hex, String namespaceID, Object data){
        this.hex = hex;
        this.namespaceID = namespaceID;
        this.data = data;
    }

    public int getHex() {
        return hex;
    }

    public String getNamespaceID() {
        return namespaceID;
    }

    public static DungeonsBlock getByHex(int hex) {
        for(DungeonsBlock block : values()) {
            if(block.getHex() == hex) return block;
        }
        return AIR;
    }

    public static DungeonsBlock getByNamespaceID(String namespaceID) {
        for(DungeonsBlock block : values()) {
            if(block.getNamespaceID().equalsIgnoreCase(namespaceID)) return block;
        }
        return AIR;
    }

    public enum SlabType{

        DOUBLE,
        BOTTOM,
        TOP

    }

}
